### ISSUE TITLE
building failures

### ISSUE THREAD

**Issue by dirteat** [amalon/osgXR#1]
Hi there,
I was trying to build the lib with cmake, but it fails searching for some funny target Threads (OpenThreads is properly found).
cmake version 3.19.2

Any help welcome.

Thanks,
Cheers,
Chris.

```
The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- Found osgViewer: /usr/lib64/libosgViewer.so
-- Found osgUtil: /usr/lib64/libosgUtil.so
-- Found osg: /usr/lib64/libosg.so
-- Found OpenThreads: /usr/lib64/libOpenThreads.so
-- Found OpenSceneGraph: /usr/lib64/libosgViewer.so;/usr/lib64/libosgUtil.so;/usr/lib64/libosg.so;/usr/lib64/libOpenThreads.so (found version "3.6.5")
-- Found X11: /usr/include
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Configuring done
CMake Error at src/CMakeLists.txt:74 (add_library):
  Target "osgXR" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

**Comment by amalon** [comment]
Hi Chris. Hmm. The only cmake style dependency osgXR has is OpenXR::openxr_loader, and indeed the OpenXR SDK refers to Threads::Threads:
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/master/src/loader/CMakeLists.txt#L124

That ends up in OpenXR::openxr_loader's INTERFACE_LINK_LIBRARIES, but it should be found from OpenXR's /usr/lib/cmake/openxr/OpenXRConfig.cmake from here:
https://github.com/KhronosGroup/OpenXR-SDK-Source/blame/master/src/loader/OpenXRConfig.cmake.in#L8

which was only added 12 months ago in OpenXR SDK 1.0.14 (2021-01-27).

What distro is this? What version of the OpenXR loader do you have?

Thanks, James

**Comment by amalon** [comment]
Can you please test that the test-issue1 branch works for you? If so and your distro is still shipping an old OpenXR loader on a supported version, I'm happy to push the workaround.

Thanks, James

**Comment by dirteat** [comment]
Thanks, I am using Mageia 8, and, indeed, OpenXR is at version 1.0.13. But if this is bug in openXR 1.0.13, I can definitely ask for a fix and bug fix update of OpenXR.
And thanks for the workaround, test-issue1 works fine! I am closing!

**Comment by amalon** [comment]
Yeh its a bug in the openxr sdk really, but I've pushed the workaround to master branch anyway so it'll be in the next release. Let me know if you hit any more issues.
Thanks
