### ISSUE TITLE
XR_ERROR_RUNTIME_UNAVAILABLE requires some minimal version for openxr?

### ISSUE THREAD

**Issue by dirteat** [amalon/osgXR#5]
Hi there,
just a comment, my system has only openxr-1.0.13 and the build of osgXR-0.5.1 fails with it. I indeed cannot find the variable in openxr.h, but I do see it in latest versions of openxr.
Maybe some conditionals on a minimal version of openxr should be added in cmake config files, or,  some preprocessor conditionals in the code itself to not use that guy for older version of openxr?

PS: tested also osgXR-0.5.1 against openxr-1.0.22, everything is fine there!

Cheers,
Chris.

**Comment by amalon** [comment]
Thanks for pointing this out, I've pushed a slightly ugly workaround to the master branch that should allow osgXR to build with older versions of the OpenXR SDK (tested back to 1.0.12). As long as it remains relatively easy to support older versions I don't see any harm in doing so.
